version: '2.1'

services:
  assetmanagement:
    image: assetmanagement
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8082:8082
      - 9229:9229
    ## set your startup file here
    command: node --inspect app.js